//-----------------------------------------------------------------------------------------
// fiber (header only)
// Copyright (C) 2022-23 Fix8 Market Technologies Pty Ltd
//   by David L. Dight
// see https://github.com/fix8mt/f8fiber
//
// Lightweight header-only stackful per-thread fiber
//		with built-in roundrobin scheduler x86_64 / linux only
//
// Distributed under the Boost Software License, Version 1.0 August 17th, 2003
//
// Permission is hereby granted, free of charge, to any person or organization
// obtaining a copy of the software and accompanying documentation covered by
// this license (the "Software") to use, reproduce, display, distribute,
// execute, and transmit the Software, and to prepare derivative works of the
// Software, and to permit third-parties to whom the Software is furnished to
// do so, all subject to the following:
//
// The copyright notices in the Software and this entire statement, including
// the above license grant, this restriction and the following disclaimer,
// must be included in all copies of the Software, in whole or in part, and
// all derivative works of the Software, unless such copies or derivative
// works are solely in the form of machine-executable object code generated by
// a source language processor.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
// SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
// FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
// ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.
//-----------------------------------------------------------------------------------------
#include <iostream>
#include <functional>
#include <deque>
#include <set>
#include <thread>
#include <fix8/f8fiber.hpp>

//-----------------------------------------------------------------------------------------
using namespace FIX8;
using namespace std::chrono_literals;

//-----------------------------------------------------------------------------------------
std::thread::id id0;

//-----------------------------------------------------------------------------------------
void sub(int arg)
{
	id0 = std::this_thread::get_id();

	std::cout << "\tstarting sub " << arg << '\n';
	for (int ii{}; ii < arg; this_fiber::yield())
	{
		std::cout << "\tsub " << std::this_thread::get_id() << ' ' << arg << ": " << ++ii << '\n';
		std::this_thread::sleep_for(500ms);
	}
	std::cout << "\tleaving sub " << arg << '\n';
}

void sub1(int arg)
{
	std::cout << "\tstarting sub1 " << arg << '\n';
	for (int ii{}; ii < arg; this_fiber::yield())
	{
		std::cout << "\tsub1 " << std::this_thread::get_id() << ' ' << arg << ": " << ++ii << '\n';
		if (ii == 5)
		{
			std::cout << "\ntransferring from " << std::this_thread::get_id() << " to " << id0 << '\n';
			this_fiber::move(id0);
		}
		std::this_thread::sleep_for(500ms);
	}
	std::cout << "\tleaving sub1 " << arg << '\n';
}

void sub2(int arg)
{
	std::cout << "\tstarting sub2 " << arg << '\n';
	for (int ii{}; ii < arg; this_fiber::yield())
	{
		std::cout << "\tsub2 " << std::this_thread::get_id() << ' ' << arg << ": " << ++ii << '\n';
		std::this_thread::sleep_for(500ms);
	}
	std::cout << "\tleaving sub2 " << arg << '\n';
}

//-----------------------------------------------------------------------------------------
int main(void)
{
	fiber f0({.name="first"},&sub, 15);
	std::thread t1([]()
	{
		fiber f1({.name="second"},&sub1, 12), f2({.name="third"},&sub2, 13);
		while (fibers::has_fibers())
		{
			std::cout << "main1\n";
			//fibers::print();
			this_fiber::yield();
		}
		std::cout << "Exiting from main1\n";
	});
	std::this_thread::sleep_for(100ms);
	while (fibers::has_fibers())
	{
		std::cout << "main\n";
		//fibers::print();
		this_fiber::yield();
	}
	std::cout << "Exiting from main\n";
	t1.join();
	return 0;
}
