//-----------------------------------------------------------------------------------------
// fiber (header only)
// Copyright (C) 2022-23 Fix8 Market Technologies Pty Ltd
//   by David L. Dight
// see https://github.com/fix8mt/fiber
//
// Lightweight header-only stackful per-thread fiber
//		with built-in roundrobin scheduler x86_64 / linux only
//
// Distributed under the Boost Software License, Version 1.0 August 17th, 2003
//
// Permission is hereby granted, free of charge, to any person or organization
// obtaining a copy of the software and accompanying documentation covered by
// this license (the "Software") to use, reproduce, display, distribute,
// execute, and transmit the Software, and to prepare derivative works of the
// Software, and to permit third-parties to whom the Software is furnished to
// do so, all subject to the following:
//
// The copyright notices in the Software and this entire statement, including
// the above license grant, this restriction and the following disclaimer,
// must be included in all copies of the Software, in whole or in part, and
// all derivative works of the Software, unless such copies or derivative
// works are solely in the form of machine-executable object code generated by
// a source language processor.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
// SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
// FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
// ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.
//-----------------------------------------------------------------------------------------
#include <iostream>
#include <string_view>
#include <functional>
#include <deque>
#include <set>
#include <fix8/f8fiber.hpp>

//-----------------------------------------------------------------------------------------
using namespace FIX8;
using namespace std::literals;

//-----------------------------------------------------------------------------------------
struct blah { ~blah() { std::cout << "~blah(): " << this_fiber::name() << '\n'; } };

void doit(int arg, std::string_view spacer)
{
	blah b;
	std::cout << spacer << "starting " << this_fiber::name() << ' ' << arg << '\n';
	for (int ii{}; ii < arg; this_fiber::yield())
		std::cout << spacer << this_fiber::name() << ' ' << arg << ": " << ++ii << '\n';
	std::cout << spacer << "leaving " << this_fiber::name() << ' ' << arg << '\n';
}

void doit_with_stoprequest(std::string_view spacer, bool& stop_requested)
{
	blah b;
	std::cout << spacer << "starting " << this_fiber::name() << '\n';
	for(int ii{};; this_fiber::yield())
	{
		std::cout << spacer << this_fiber::name() << ": " << ++ii << '\n';
		if (stop_requested)
		{
			std::cout << spacer << this_fiber::name() << ": stop requested\n";
			break;
		}
	}
	std::cout << spacer << "leaving " << this_fiber::name() << '\n';
}

//-----------------------------------------------------------------------------------------
int main(void)
{
	fiber sub_co({.name="sub0"}, &doit, 9, "\t"), sub_co1({.name="sub1"}, [](int arg, std::string_view spacer)
	{
		blah b;
		bool stop_requested{};
		std::cout << spacer << "starting " << this_fiber::name() << ' ' << arg << '\n';
		fiber sub_co2({.name="sub1/sub",.join=true}, &doit_with_stoprequest, "\t\t", std::ref(stop_requested));
		for (int ii{}; ii < arg; this_fiber::yield())
			std::cout << spacer << this_fiber::name() << ' ' << arg << ": " << ++ii << '\n';
		stop_requested = true;
		std::cout << spacer << "leaving " << this_fiber::name() << ' ' << arg << '\n';
	}, 10, "\t");
	fibers::print();
	for (int ii{}; fibers::has_fibers(); ++ii)
	{
		std::cout << "main: " << std::dec << ii << '\n';
		this_fiber::yield();
		if (ii == 1)
			fibers::print();
	}
	std::cout << "Exiting from main\n";
	return 0;
}
