//-----------------------------------------------------------------------------------------
// fiber (header only)
// Copyright (C) 2022-23 Fix8 Market Technologies Pty Ltd
//   by David L. Dight
// see https://github.com/fix8mt/fiber
//
// Lightweight header-only stackful per-thread fiber
//		with built-in roundrobin scheduler x86_64 / linux only
//
// Distributed under the Boost Software License, Version 1.0 August 17th, 2003
//
// Permission is hereby granted, free of charge, to any person or organization
// obtaining a copy of the software and accompanying documentation covered by
// this license (the "Software") to use, reproduce, display, distribute,
// execute, and transmit the Software, and to prepare derivative works of the
// Software, and to permit third-parties to whom the Software is furnished to
// do so, all subject to the following:
//
// The copyright notices in the Software and this entire statement, including
// the above license grant, this restriction and the following disclaimer,
// must be included in all copies of the Software, in whole or in part, and
// all derivative works of the Software, unless such copies or derivative
// works are solely in the form of machine-executable object code generated by
// a source language processor.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
// SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
// FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
// ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.
//
// Monitor test using:
//
// Termbox2
//		MIT License
// 	Copyright (c) 2010-2020 nsf <no.smile.face@gmail.com>
//		              2015-2022 Adam Saponara <as@php.net>
//-----------------------------------------------------------------------------------------
#include <iostream>
#include <chrono>
#include <thread>
#include <random>
#include <fix8/fiber.hpp>
#include <fix8/fibermonitor.hpp>
#include <unistd.h>
#include <getopt.h>

//-----------------------------------------------------------------------------------------
using namespace FIX8;
using namespace std::literals;

//-----------------------------------------------------------------------------------------
class foo : public fiber_monitor
{
	std::mt19937_64 _rnde {std::random_device{}()};
	std::uniform_int_distribution<int> _dist{1, 224};
	int _sleepval, _val;
	window_frame _xyxy;

public:
	foo(int sleepval, std::chrono::milliseconds timeout, sort_mode mode)
		: fiber_monitor(timeout, mode), _sleepval(sleepval), _xyxy({{}, {get_dimensions().first, get_dimensions().second}}) {}

	void func(int arg)
	{
		this_fiber::name("sub"s + std::to_string(arg));
		auto num { 2 * ++arg };
		while (num--)
		{
			double varr[arg * _dist(_rnde)]; // consume variable amt of stack
			_val = varr[_dist(_rnde)]; // force optimizer hands off

			update(_xyxy);
			if (!*this)
				this_fiber::resume_main();
			std::this_thread::sleep_for(std::chrono::milliseconds(_sleepval));
			this_fiber::yield();
		}
	}
};

//-----------------------------------------------------------------------------------------
int main(int argc, char *argv[])
{
	constexpr int sleep_default{50}, interval_default{100};
	int interval{interval_default}, fcnt{-1}, sleepval{sleep_default};
	bool lorder{true}, skip{true};
	fiber_monitor::sort_mode sm{ fiber_monitor::sort_mode::by_ms };

	static constexpr auto optstr { "f:i:s:om:rkh" };
   static constexpr const std::array long_options
   {
      option{ "help",		no_argument,			0, 'h' },	option{ "retain",		no_argument,			0, 'r' },
		option{ "order",		no_argument,			0, 'o' },	option{ "noskip",		no_argument,			0, 'k' },
		option{ "sleep",		required_argument,	0, 's' },	option{ "interval",	required_argument,	0, 'i' },
      option{ "fibers",		required_argument,	0, 'f' },	option{ "mode",		required_argument,	0, 'm' },
      option{}
   };

	for (int val; (val = getopt_long (argc, argv, optstr, long_options.data(), 0)) != -1; )
	{
		try
		{
			switch (val)
			{
			case 'm':
				if (auto ism{ std::stoul(optarg) - 1UL }; ism < static_cast<long unsigned>(fiber_monitor::sort_mode::count))
					sm = fiber_monitor::sort_mode(ism);
				break;
			case 'f': fcnt = std::stoi(optarg); break;
			case 's': sleepval = std::stoi(optarg); break;
			case 'r': fibers::set_flag(global_fiber_flags::retain); break;
			case 'k': skip ^= true; break;
			case 'o': lorder ^= true; break;
			case 'i': interval = std::stoi(optarg); break;
			case '?':
			case ':':
			case 'h':
				std::cout << "Usage: " << argv[0] << " -[" << optstr << R"(]
  -i,--interval interval msecs (default )" << interval << R"()
  -f,--fibers fiber count (default )" << (fiber_monitor::get_terminal_dimensions().second - 4) << R"()
  -s,--sleep sleep msecs (default )" << sleepval << R"()
  -m,--mode sort mode )" << fiber_monitor::sort_help() << "(default " << (static_cast<long unsigned>(sm) + 1) << R"()
  -o,--order no launch order
  -k,--noskip no skip main
  -r,--retain retain finished fibers (default false)
  -h,--help)
e.g.
  ./montest1 --mode 8 --retain --interval 0 --sleep 25)" << std::endl;
				exit(1);
			default:
				break;
			}
		}
		catch (const std::exception& e)
		{
			std::cerr << "exception: " << e.what();
			if (optarg)
				std::cerr << " (" << static_cast<char>(val) << ':' << optarg << ')';
			std::cerr << std::endl;
			exit(1);
		}
	}

	if (skip)
		fibers::set_flag(global_fiber_flags::skipmain);
	foo bar(sleepval, std::chrono::milliseconds(interval), sm);
	if (fcnt == -1)
		fcnt = bar.get_dimensions().second - 4;
	std::vector<fiber_ptr> fbs;
	for (int ii{}; ii < fcnt; ++ii)
		fbs.emplace_back(make_fiber({.launch_order=lorder ? ii : 99,.stacksz=(fcnt * 4096lu) & ~0xff}, &foo::func, &bar, ii));

	fibers::wait_all([&bar]()
	{
		if (!bar)
			fibers::kill_all();
		return !bar;
	});
	bar.update();
	std::this_thread::sleep_for(2s);
	return 0;
}
