//-----------------------------------------------------------------------------------------
// fiber (header only)
// Copyright (C) 2022-23 Fix8 Market Technologies Pty Ltd
//   by David L. Dight
// see https://github.com/fix8mt/fiber
//
// Lightweight header-only stackful per-thread fiber
//		with built-in roundrobin scheduler x86_64 / linux only
//
// Distributed under the Boost Software License, Version 1.0 August 17th, 2003
//
// Permission is hereby granted, free of charge, to any person or organization
// obtaining a copy of the software and accompanying documentation covered by
// this license (the "Software") to use, reproduce, display, distribute,
// execute, and transmit the Software, and to prepare derivative works of the
// Software, and to permit third-parties to whom the Software is furnished to
// do so, all subject to the following:
//
// The copyright notices in the Software and this entire statement, including
// the above license grant, this restriction and the following disclaimer,
// must be included in all copies of the Software, in whole or in part, and
// all derivative works of the Software, unless such copies or derivative
// works are solely in the form of machine-executable object code generated by
// a source language processor.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
// SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
// FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
// ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.
//
// Monitor test using:
//
// GNU multiple precision arithmetic library, version 6.2.1.
// 	Copyright 1991, 1993-2016, 2018-2020 Free Software Foundation, Inc.
// Termbox2
//		MIT License
// 	Copyright (c) 2010-2020 nsf <no.smile.face@gmail.com>
//		              2015-2022 Adam Saponara <as@php.net>
//----------------------------------------------------------------------------------------

#include <iostream>
#include <fstream>
#include <chrono>
#include <thread>
#include <random>
#include <fix8/f8fiber.hpp>
#include <fix8/f8fibermonitor.hpp>
#include <getopt.h>
#include <gmpxx.h>

//-----------------------------------------------------------------------------------------
using namespace FIX8;
using namespace std::literals;

//-----------------------------------------------------------------------------------------
class foo : public fiber_monitor
{
	std::mt19937_64 _rnde {std::random_device{}()};
	std::uniform_int_distribution<long> _exp;
	bool _todisk;

public:
	foo(int interval, long maxexp, bool todisk) :
		fiber_monitor(std::chrono::milliseconds(interval), fiber_monitor::sort_mode::by_ms),
		_exp{1, maxexp}, _todisk(todisk) {}

	void func(int arg)
	{
		std::unique_ptr<std::ofstream> ofstr { _todisk ? std::make_unique<std::ofstream>(
			std::string { "worker"s + std::to_string(arg - 10) + ".out" }.c_str(), std::ios::trunc) : nullptr };

		while(arg--)
		{
			auto expv { _exp(_rnde) }; // obtain our exponent
			std::ostringstream ostr;
			ostr << "2^" << expv;
			this_fiber::name(ostr.str().c_str());
			update();
			mpz_class pr;
			mpz_ui_pow_ui(pr.get_mpz_t(), 2, expv); // raise 2^expv
			if (ofstr)
				*ofstr << ostr.str() << " = " << pr << '\n';
			update();
			is_quit() ? this_fiber::resume_main() : this_fiber::yield(); // user pressed 'x'?
		}
		this_fiber::name("finished");
	}
};

//-----------------------------------------------------------------------------------------
int main(int argc, char *argv[])
{
	int interval{}, fcnt{20}, val;
	long maxexp{4999999999L};
	bool todisk{}, threaded{}, retain{true};

	option long_options[]
	{
		{ "help",		no_argument,			nullptr, 'h' },
		{ "write",		no_argument,			nullptr, 'w' },
		{ "fibers",		required_argument,	nullptr, 'f' },
		{ "maxexp",		required_argument,	nullptr, 'm' },
		{ "interval",	required_argument,	nullptr, 'i' },
		{},
	};

	static constexpr const char *optstr{"f:i:hm:wr"};
	while ((val = getopt_long (argc, argv, optstr, long_options, 0)) != -1)
	{
		try
		{
			switch (val)
			{
			case ':': case '?':
				std::cout << '\n';
				[[fallthrough]];
			case 'h':
				std::cout << "Usage: " << argv[0] << " [-" << optstr << "]" << R"(
  -w write results to disk files (default false)
  -i interval msecs (default 0)
  -r retain finished fibers (default true)
  -f fiber count (default 20)
  -m max exponent (default 4999999999)
  -h help)" << std::endl;
			  return 0;
			case 'w': todisk = true; break;
			case 'r': retain = false; break;
			case 'm': maxexp = std::stol(optarg); break;
			case 'f': fcnt = std::stoi(optarg); break;
			case 'i': interval = std::stoi(optarg); break;
			default: break;
			}
		}
		catch (const std::exception& e)
		{
			std::cerr << optarg << ": error: invalid value for switch \'"
				<< static_cast<char>(val) << "\' (" << e.what() << ')' << std::endl;
			return 1;
		}
	}

	if (todisk && maxexp == 4999999999L)
		maxexp = 10000000L;
	if (retain)
		fibers::set_flag(global_fiber_flags::retain);

	foo bar(interval, maxexp, todisk);
	std::vector<fiber_ptr> fbs;
	for (int ii{}; ii < fcnt; ++ii)
		fbs.emplace_back(make_fiber({.launch_order=ii}, &foo::func, &bar, ii + 10));

	while (fibers::has_fibers())
	{
		this_fiber::yield();
		if (!bar)
		{
			fibers::kill_all();
			break;
		}
	}
	bar.update();
	std::this_thread::sleep_for(3s);
	return 0;
}
