//-----------------------------------------------------------------------------------------
// f8_sched_fiber (header only)
// Copyright (C) 2022 Fix8 Market Technologies Pty Ltd
// see https://github.com/fix8mt/f8fiber
//
// Lightweight header-only stackful per-thread fiber
//		with built-in roundrobin scheduler x86_64 / linux only
//
// Distributed under the Boost Software License, Version 1.0 August 17th, 2003
//
// Permission is hereby granted, free of charge, to any person or organization
// obtaining a copy of the software and accompanying documentation covered by
// this license (the "Software") to use, reproduce, display, distribute,
// execute, and transmit the Software, and to prepare derivative works of the
// Software, and to permit third-parties to whom the Software is furnished to
// do so, all subject to the following:
//
// The copyright notices in the Software and this entire statement, including
// the above license grant, this restriction and the following disclaimer,
// must be included in all copies of the Software, in whole or in part, and
// all derivative works of the Software, unless such copies or derivative
// works are solely in the form of machine-executable object code generated by
// a source language processor.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
// SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
// FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
// ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.
//----------------------------------------------------------------------------------------
#ifndef FIX8_SCHEDFIBER_HPP_
#define FIX8_SCHEDFIBER_HPP_

//----------------------------------------------------------------------------------------
#include <iostream>
#include <iomanip>
#include <type_traits>
#include <future>
#include <deque>
#include <chrono>
#include <algorithm>
#include <cstring>
#include <functional>
#include <stdexcept>
#include <bitset>
#include <mutex>
#include <condition_variable>
#include <set>

//-----------------------------------------------------------------------------------------
#if !defined SIGSTKSZ
# define SIGSTKSZ 131072 // 128kb recommended
#endif
#if !defined FIBERNAMELEN
# define FIBERNAMELEN 16 // including null terminator
#endif

//-----------------------------------------------------------------------------------------
namespace FIX8 {

//-----------------------------------------------------------------------------------------
#if !defined f8_nonconstructible
/// simple non-constructable base
class f8_nonconstructible
{
protected:
	f8_nonconstructible() = delete;
	~f8_nonconstructible() = delete;
};
#endif

//-----------------------------------------------------------------------------------------
/// unique fiber id
class f8_fiber_id
{
	const void *_ptr{ nullptr };

public:
	f8_fiber_id() = default;
	explicit f8_fiber_id(const void *ptr) noexcept : _ptr{ ptr } {}

#if __cplusplus >= 202002L
	constexpr auto operator<=>(const f8_fiber_id& other) const noexcept { return _ptr <=> other._ptr; }
#else
	constexpr bool operator==(const f8_fiber_id& other) const noexcept { return _ptr == other._ptr; }
	constexpr bool operator!=(const f8_fiber_id& other) const noexcept { return _ptr != other._ptr; }
	constexpr bool operator<(const f8_fiber_id& other) const noexcept { return _ptr < other._ptr; }
	constexpr bool operator>(const f8_fiber_id& other) const noexcept { return other._ptr < _ptr; }
	constexpr bool operator<=(const f8_fiber_id& other) const noexcept { return !(*this > other); }
	constexpr bool operator>=(const f8_fiber_id& other) const noexcept { return !(*this < other); }
#endif

	template<typename charT, class traitsT>
	friend std::basic_ostream<charT, traitsT>& operator<<(std::basic_ostream<charT, traitsT>& os, const f8_fiber_id& what)
	{
		if (what._ptr)
			return os << std::dec << reinterpret_cast<uint64_t>(what._ptr);
		return os << "not a fiber";
	}

	constexpr explicit operator bool() const noexcept { return _ptr != nullptr; }
	constexpr bool operator!() const noexcept { return _ptr == nullptr; }

	friend class f8_this_fiber;
};

//-----------------------------------------------------------------------------------------
class f8_this_fiber : protected f8_nonconstructible
{
public:
	static f8_fiber_id get_id() noexcept;
	static class f8_sched_fiber& get() noexcept;
	static class f8_sched_fiber& get(f8_fiber_id id);
	static void yield() noexcept;
	static void yield(f8_fiber_id id) noexcept;
	template<typename Clock, typename Duration>
	static void sleep_until(std::chrono::time_point<Clock, Duration> const& sleep_time);
	template<typename Rep, typename Period>
	static void sleep_for(std::chrono::duration<Rep, Period> const& rel_time);
};

class f8_fibers : protected f8_nonconstructible
{
public:
	static int size() noexcept;
	static int size_ready() noexcept;
	static bool has_fibers() noexcept;
	static bool has_ready_fibers() noexcept;
	static void print(std::ostream& os) noexcept;
};

//-----------------------------------------------------------------------------------------
class fiber_error : public std::system_error // from boost::fiber
{
public:
	explicit fiber_error(std::error_code ec) : std::system_error{ec} {}
	fiber_error(std::error_code ec, const char *what_arg) : std::system_error{ec, what_arg} {}
	fiber_error(std::error_code ec, const std::string& what_arg) : std::system_error{ec, what_arg} {}
};

template<typename T>
struct is_launch_policy : public std::false_type {}; // from boost::fiber

enum class launch { dispatch, post }; // from boost::fiber

template<>
struct is_launch_policy<launch> : public std::true_type {}; // from boost::fiber

template<typename T>
inline constexpr bool is_launch_policy_v = is_launch_policy<T>::value; // C++14 enhancement

//-----------------------------------------------------------------------------------------
class alignas(16) f8_sched_fiber
{
	enum f8_fiber_flags { main, finished, suspended, dispatched, detached, count };

	uintptr_t *_stk; // top of f8_sched_fiber stack
	const uintptr_t _stacksz;
	uintptr_t *_stk_alloc{}; // allocated stack memory
	const char *_name;
	std::bitset<f8_fiber_flags::count> _flags;
	std::chrono::steady_clock::time_point _tp{};
	std::condition_variable _cv_join;
	std::mutex _join_mutex;

	struct cvars
	{
		std::set<f8_sched_fiber *> _uniq;
		std::deque<f8_sched_fiber *> _sched;
		f8_sched_fiber *_curr;
	};
	static cvars& get_vars() noexcept
	{
		static thread_local f8_sched_fiber _def_fiber;
		static thread_local cvars _cvars{._uniq={&_def_fiber},._curr=&_def_fiber};
		return _cvars;
	}

	static void f8_sched_fiber_exit()
	{
		std::cout << "f8_sched_fiber has exited. Terminating application.\n";
		std::terminate();
	}

	template<typename Fn>
	class callable_wrapper
	{
		typename std::decay_t<Fn> _func;

	public:
		callable_wrapper(Fn&& func) noexcept : _func(std::forward<Fn>(func)) {}
		~callable_wrapper() = default;

		void exec()
		{
			_func();
			auto& [un, sch, cur] { get_vars() };
			cur->_flags.set(f8_fiber_flags::finished);
			if (!sch.empty())
				f8_this_fiber::yield();
			f8_sched_fiber_exit();
		}
	};

	template<typename Wrapper>
	static void jumper(void *ptr) { static_cast<Wrapper*>(ptr)->exec(); }

	// asm stack switch routine
	static void _coroswitch(f8_sched_fiber *old, f8_sched_fiber *newer) noexcept;

	// default current (main) f8_sched_fiber
	f8_sched_fiber() noexcept : _stacksz{}, _name{"main"}, _flags{1 << f8_fiber_flags::main} {}

public:
	template<typename Fn, typename... Args, std::enable_if_t<!std::is_bind_expression_v<Fn>,int> = 0>
	f8_sched_fiber(Fn&& func, Args&&... args)
		: f8_sched_fiber(launch::post, std::bind(std::forward<Fn>(func), std::forward<Args>(args)...)) {}

	template<typename Fn, typename... Args, std::enable_if_t<!std::is_bind_expression_v<Fn>,int> = 0>
	f8_sched_fiber(launch policy, Fn&& func, Args&&... args)
		: f8_sched_fiber(policy, std::bind(std::forward<Fn>(func), std::forward<Args>(args)...)) {}

	template<typename Fn>
	f8_sched_fiber(Fn&& func, size_t stacksz=SIGSTKSZ)
		: f8_sched_fiber(launch::post, std::forward<Fn>(func), stacksz) {}

	template<typename Fn, typename Wrapper = callable_wrapper<Fn>>
	f8_sched_fiber(launch policy, Fn&& func, size_t stacksz=SIGSTKSZ)
		: _stacksz(stacksz & ~static_cast<uintptr_t>(0xff)), _stk_alloc(new uintptr_t[_stacksz / sizeof(uintptr_t)])
	{
		_stk = _stk_alloc + _stacksz / sizeof(uintptr_t) - 1; // top of stack
		*--_stk = reinterpret_cast<uintptr_t>(jumper<Wrapper>);
		*--_stk = reinterpret_cast<uintptr_t>(new (reinterpret_cast<char*>(_stk_alloc)) callable_wrapper(std::forward<Fn>(func))); // store at bottom of stack
		_name = new (reinterpret_cast<char*>(_stk_alloc) + sizeof(callable_wrapper<Fn>)) char[FIBERNAMELEN]; // place optional name in stack
		std::fill(_stk -= 7, _stk, 0x0);
		auto& [un, sch, cur] { get_vars() };
		un.insert(this);
		sch.push_back(this);
		if (policy == launch::dispatch)
		{
			_flags.set(f8_fiber_flags::dispatched);
			f8_this_fiber::yield();
		}
	}

	f8_sched_fiber(const f8_sched_fiber&) = delete;
	f8_sched_fiber& operator=(const f8_sched_fiber&) = delete;

	~f8_sched_fiber()
	{
		if (!_flags[f8_fiber_flags::main])
		{
			delete[] _stk_alloc;
			if (joinable())
				f8_sched_fiber_exit();
		}
	}

	f8_sched_fiber(f8_sched_fiber&& other) noexcept : _stacksz{other._stacksz}
	{
		swap(other);
		other.detach();
	}
	f8_sched_fiber& operator=(f8_sched_fiber&& other) noexcept
	{
		if (joinable())
			std::terminate();
		if (this != &other)
			swap(other);
		return *this;
	}

	void join()
	{
		if (auto& cur { get_vars()._curr }; this != cur)
		{
			if (!joinable())
				throw fiber_error { std::make_error_code(std::errc::invalid_argument),
					"f8_sched_fiber: fiber not joinable" };
			else
			{
				std::unique_lock jlock(_join_mutex);
				_cv_join.wait(jlock, [this]{ return !joinable();});
			}
		}
		else
			throw fiber_error { std::make_error_code(std::errc::resource_deadlock_would_occur),
				"f8_sched_fiber: fiber cannot self-join" };
	}

	bool joinable() const noexcept { return !_flags[f8_fiber_flags::finished]; };
	void detach()
	{
		if (joinable())
		{
			_flags.set(f8_fiber_flags::detached);
			get_vars()._uniq.erase(this);
		}
		else
			throw fiber_error { std::make_error_code(std::errc::invalid_argument),
				"f8_sched_fiber: fiber not joinable" };
	}

	const char *name(const char *what=nullptr)
	{
		if (what && !_flags[f8_fiber_flags::main]) // you can't name main
		{
			const size_t len { std::strlen(what) }	;
			std::memcpy(const_cast<char*>(_name), what, len + 1 > FIBERNAMELEN ? FIBERNAMELEN - 1 : len);
			const_cast<char*>(_name)[len] = 0;
		}
		return _name;
	}
	void swap(f8_sched_fiber& other)
	{
		if (this != &other)
		{
			std::swap(_stk, other._stk);
			std::swap(_stk_alloc, other._stk_alloc);
			std::swap(_flags, other._flags);
			std::swap(_tp, other._tp);
		}
	}

	static void swap(f8_sched_fiber& first, f8_sched_fiber& second) { first.swap(second); }

	explicit operator bool() const noexcept { return joinable(); }
	bool operator! () const noexcept { return !joinable(); }

	launch get_policy() const noexcept { return _flags[f8_fiber_flags::dispatched] ? launch::dispatch : launch::post; }
	f8_fiber_id get_id() const noexcept { return f8_fiber_id(!_flags[f8_fiber_flags::main] ? this : nullptr); }

	friend std::ostream& operator<<(std::ostream& os, const f8_sched_fiber& what)
	{
		return os << std::hex << &what << ' ' << std::left << std::setw(5)
			<< (&what == f8_sched_fiber::get_vars()._curr ? '*' : ' ')
			<< std::left << std::setw(15) << what.get_id()
			<< ' ' << std::setw(14) << what._stk
			<< ' ' << std::setw(14) << what._stk_alloc
			<< ' ' << std::right << std::setw(8) << what._stacksz
			<< ' ' << what._flags << ' ' << what._name; // << " (" << reinterpret_cast<const void*>(what._name) << ')';
	}
	friend f8_this_fiber;
	friend f8_fibers;
};

//-----------------------------------------------------------------------------------------
// static void f8_sched_fiber::_coroswitch(f8_sched_fiber *old, f8_sched_fiber *newer) noexcept;
asm(R"(.text
.align 16
.type _ZN4FIX814f8_sched_fiber11_coroswitchEPS0_S1_,@function
_ZN4FIX814f8_sched_fiber11_coroswitchEPS0_S1_:
	subq $0x40,%rsp
   stmxcsr (%rsp)
   fnstcw  4(%rsp)
	movq %r15,8(%rsp)
	movq %r14,8*2(%rsp)
	movq %r13,8*3(%rsp)
	movq %r12,8*4(%rsp)
	movq %rbx,8*5(%rsp)
	movq %rbp,8*6(%rsp)
	movq %rdi,8*7(%rsp)

	mov %rsp,(%rdi)
	mov (%rsi),%rsp

   ldmxcsr (%rsp)
   fldcw  4(%rsp)
   movq 8(%rsp),%r15
   movq 8*2(%rsp),%r14
   movq 8*3(%rsp),%r13
   movq 8*4(%rsp),%r12
   movq 8*5(%rsp),%rbx
   movq 8*6(%rsp),%rbp
   movq 8*7(%rsp),%rdi
	movq 8*8(%rsp),%r8
	addq $0x48,%rsp
   jmp *%r8
.size _ZN4FIX814f8_sched_fiber11_coroswitchEPS0_S1_,.-_ZN4FIX814f8_sched_fiber11_coroswitchEPS0_S1_
)");

//-----------------------------------------------------------------------------------------
// custom async, uses f8_sched_fiber, modified boost::fiber::async
template<typename Fn, typename... Args>
std::future<typename std::result_of_t<typename std::enable_if_t<!is_launch_policy_v
	<typename std::decay_t<Fn>>, typename std::decay_t<Fn>>(typename std::decay_t<Args>...)>>
async(Fn&& fn, Args... args)
{
	using result_type = typename std::result_of_t<typename std::decay_t<Fn>(typename std::decay_t<Args>...)>;
	std::packaged_task<result_type(typename std::decay_t<Args>...)> task { std::forward<Fn>(fn) };
	std::future<result_type> fut { task.get_future() };
	f8_sched_fiber(std::move(task), std::forward<Args>(args)...).detach();
	return fut;
}

template<typename Fn, typename... Args>
std::future<typename std::result_of_t
	<typename std::decay_t<Fn>(typename std::decay_t<Args>...)>>
async(launch policy, Fn&& fn, Args... args)
{
	using result_type = typename std::result_of_t<typename std::decay_t<Fn>(typename std::decay_t<Args>...)>;
	std::packaged_task<result_type(typename std::decay_t<Args>...)> task { std::forward<Fn>(fn) };
	std::future<result_type> fut { task.get_future() };
	f8_sched_fiber(policy, std::move(task), std::forward<Args>(args)...).detach();
	return fut;
}

//-----------------------------------------------------------------------------------------
f8_fiber_id f8_this_fiber::get_id() noexcept { return f8_sched_fiber::get_vars()._curr->get_id(); }

void f8_this_fiber::yield() noexcept
{
	auto& [un, sch, cur] { f8_sched_fiber::get_vars() };
	while (!sch.empty())
	{
		auto& front { sch.front() };
		sch.pop_front();
		if (!front->_flags[f8_sched_fiber::f8_fiber_flags::finished] && un.count(front))
		{
			if (front->_flags[f8_sched_fiber::f8_fiber_flags::suspended])
			{
				if (front->_tp < std::chrono::steady_clock::now())
				{
					front->_flags.reset(f8_sched_fiber::f8_fiber_flags::suspended);
					front->_tp = decltype(front->_tp)();
				}
				else
				{
					sch.push_back(front);
					continue;
				}
			}
			std::swap(front, cur);
			sch.push_back(front);
			f8_sched_fiber::_coroswitch(front, cur);
			break;
		}
		else
			un.erase(front);
	}
}
void f8_this_fiber::yield(f8_fiber_id id) noexcept
{
	auto& [un, sch, cur] { f8_sched_fiber::get_vars() };
	if (auto *fbr { static_cast<f8_sched_fiber*>(const_cast<void*>(id._ptr)) }; cur != fbr && un.count(fbr))
	{
		if (auto& front { sch.front() }; front != fbr)
		{
			for (auto itr { sch.begin() }; itr != sch.end(); ++itr)
			{
				if (*itr == fbr)
				{
					std::swap(*itr, front); // swap next with specified fiber
					break;
				}
			}
		}
		yield();
	}
}
template<typename Clock, typename Duration>
void f8_this_fiber::sleep_until(std::chrono::time_point<Clock, Duration> const& sleep_time)
{
	auto& cur { f8_sched_fiber::get_vars()._curr };
	cur->_tp = std::chrono::steady_clock::now() + (sleep_time - Clock::now());
	cur->_flags.set(f8_sched_fiber::f8_fiber_flags::suspended);
	yield();
}
template<typename Rep, typename Period>
void f8_this_fiber::sleep_for(std::chrono::duration<Rep, Period> const& rel_time)
{
	auto& cur { f8_sched_fiber::get_vars()._curr };
	cur->_tp = std::chrono::steady_clock::now() + rel_time;
	cur->_flags.set(f8_sched_fiber::f8_fiber_flags::suspended);
	yield();
}
f8_sched_fiber& f8_this_fiber::get() noexcept { return *f8_sched_fiber::get_vars()._curr; }
f8_sched_fiber& f8_this_fiber::get(f8_fiber_id id)
{
	auto& un { f8_sched_fiber::get_vars()._uniq };
	if (auto *fbr { static_cast<f8_sched_fiber*>(const_cast<void*>(id._ptr)) }; un.count(fbr))
		return *fbr;
	throw fiber_error { std::make_error_code(std::errc::invalid_argument),
		"f8_sched_fiber: unknown fiber" };
}
//-----------------------------------------------------------------------------------------
int f8_fibers::size() noexcept { return f8_sched_fiber::get_vars()._sched.size(); }
int f8_fibers::size_ready() noexcept
{
	auto& [un, sch, cur] { f8_sched_fiber::get_vars() };
	return std::count_if(un.cbegin(), un.cend(), [&cur](f8_sched_fiber *pp)
	{
		return pp != cur && !pp->_flags[f8_sched_fiber::f8_fiber_flags::suspended]
			&& !pp->_flags[f8_sched_fiber::f8_fiber_flags::finished];
	});
}
bool f8_fibers::has_fibers() noexcept { return size(); }
bool f8_fibers::has_ready_fibers() noexcept { return size_ready(); }
void f8_fibers::print(std::ostream& os) noexcept
{
	os << "#  address        this fiber id        stack ptr      stack alloc     stacksz flags name \n";
	int pos{};
	auto& [un, sch, cur] { f8_sched_fiber::get_vars() };
	os << std::left << std::setw(3) << pos++ << *cur << std::endl;
	for (const auto& pp : sch)
		os << std::left << std::setw(3) << pos++ << *pp << std::endl;
}

//-----------------------------------------------------------------------------------------
//-----------------------------------------------------------------------------------------
namespace this_fiber
{
	inline f8_fiber_id get_id() noexcept { return f8_this_fiber::get_id(); }
	inline void yield() noexcept { return f8_this_fiber::yield(); }
	inline void yield(f8_fiber_id id) noexcept { return f8_this_fiber::yield(id); }
	inline f8_sched_fiber& get() noexcept { return f8_this_fiber::get(); }
	inline f8_sched_fiber& get(f8_fiber_id id) { return f8_this_fiber::get(id); }
	inline const char *name(const char *what=nullptr) noexcept { return f8_this_fiber::get().name(what); }

	template<typename Clock, typename Duration>
	inline void sleep_until(std::chrono::time_point<Clock, Duration> const& sleep_time)
		{ return f8_this_fiber::sleep_until(sleep_time); }

	template<typename Rep, typename Period>
	inline void sleep_for(std::chrono::duration<Rep, Period> const& rel_time)
		{ return f8_this_fiber::sleep_for(rel_time); }
}

namespace fibers
{
	inline int size() noexcept { return f8_fibers::size(); }
	inline int size_ready() noexcept { return f8_fibers::size_ready(); }
	inline bool has_fibers() noexcept { return fibers::size(); }
	inline bool has_ready_fibers() noexcept { return fibers::size_ready(); }
	inline void print(std::ostream& os) noexcept { f8_fibers::print(os); }
};

} // namespace FIX8

#endif // FIX8_SCHEDFIBER_HPP_
